networks:
  web-network:
    driver: bridge

services:
  flask-app:
    build: ./flask_app
    container_name: flask-app
    restart: always
    networks:
      - web-network

  modsec-proxy:
    build: ./modsec-proxy
    container_name: modsec-proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./modsec_logs:/var/log/apache2/
    networks:
      - web-network
    depends_on:
      - flask-app