filebeat.inputs:
  - type: log
    paths:
      - /var/log/modsec_logs/modsec_audit.log
    multiline.pattern: '^\-\-'
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
