# ModSecurity 테스트 룰 파일
# 생성 시간: 2025-08-04T09:39:39.677266


# SQL Injection 차단 - 2025-08-04T09:42:52.327924
SecRule ARGS "@detectSQLi" "id:100001,phase:2,deny,msg:'SQL Injection detected'"

# XSS 공격 차단 - 2025-08-04T09:42:54.344455
SecRule ARGS "@detectXSS" "id:100002,phase:2,deny,msg:'XSS attack detected'"

# Path Traversal 차단 - 2025-08-04T09:42:56.358378
SecRule ARGS "@contains ../" "id:100003,phase:2,deny,msg:'Path traversal detected'"
