filebeat.modules:
- module: apache
  access:
    enabled: false
  error:
    enabled: false
  audit:
    enabled: true
    var.paths: ["/var/log/apache2/modsec_audit.log"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.ilm:
  enabled: true
  policy_name: "filebeat"
  rollover_alias: "filebeat"
  pattern: "{now/d}-000001"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~