logging.level: debug
logging.selectors: ["*"]

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/apache2/modsec_audit.log
  tail_files: true
  multiline:
    pattern: '^--[0-9a-f]{8}-A--'
    negate: true
    match: after

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # pipeline: "modsec-audit-parser-v1"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~